stages:
- stage: Build
  displayName: Build and Push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        containerRegistry: 'efsoft'
        command: 'build'
        repository: 'efsoft_inventory_function'
        dockerfile: '**/Dockerfile'
        arguments: '--build-arg NUGET_PASSWORD=$(PAT)'
        tags: $(Build.BuildId)
    - task: Docker@2
      displayName: 'Push Docker image'
      inputs:
        containerRegistry: 'efsoft'
        repository: 'efsoft_inventory_function'
        command: 'push'
        tags: $(Build.BuildId)