stages:
- stage: Build
  displayName: Build and Push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        containerRegistry: 'efsoft'
        command: 'build'
        repository: 'efsoft-inventory-function'
        dockerfile: '**/DockerfileFunction'
        arguments: '--build-arg NUGET_PASSWORD=$(PAT)'
        tags: latest
    - task: Docker@2
      displayName: 'Push Docker image'
      inputs:
        containerRegistry: 'efsoft'
        repository: 'efsoft-inventory-function'
        command: 'push'
        tags: latest
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(agent.builddirectory)'
        Contents: $(agent.builddirectory)/**/k8s-function-deployment.yaml
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'